### PR TITLE
dependency upgrades

### PR DESCRIPTION
**Pull request by deelawn**
The osmosis worker needs to make use of the wasm module code which utilizes ibc-go v2.  This upgrade is necessary to avoid importing both ibc-go v1 and v2 which causes a panic when registering the same error types twice upon module initialization.

### CODE REVIEW

**Comment by lukanus** [comment]
The only question would be: "how about different networks"

**Comment by deelawn** [comment]
Good question.  How would we figure that out? Look at their SDKs and check which version of ibc-go (if any) they are using? We could also tag the current release as v1 and make this v2 if we need to maintain compatibility for both versions of the ibc-go module.

**Comment by lukanus** [comment]
btw it this still needed  ?

**Comment by christophermanning** [comment]
With the addition of https://github.com/figment-networks/ni-cosmoslib/pull/11, this is no longer needed.

**Pull request closed without merging**
